updating pipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,18 +26,13 @@ jobs:
 
       - name: Check if /health is accessible
         run: |
-          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/health)
-          if [ $response -ne 200 ]; then
-            echo "Health check failed with status code: $response"
-            exit 1
+          response=$(curl -s http://localhost:8000/health/)
+          echo "Response: $response"
+          if [ "$response" == '{"status":"Active"}' ]; then
+            echo "Health check passed"
           else
-            content=$(curl -s http://localhost:8000/health)
-            if [[ "$content" == *"status\":\"Active"* ]]; then
-              echo "Health check passed"
-            else
-              echo "Health check failed: Unexpected content $content"
-              exit 1
-            fi
+            echo "Health check failed"
+            exit 1
           fi
 
   FastApi-backend:
