Re-organising the pipeline to run from docker image

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,6 +3,43 @@ name: FastAPI CI
 on: [push, pull_request]
 
 jobs:
+  build-and-run:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
+      - name: Build Docker image
+        run: |
+          cd backend
+          docker build -t aora_backend .
+
+      - name: Run Docker container
+        run: |
+          docker run -d -p 8000:8000 --name aora_backend aora_backend
+          sleep 10
+          echo "FastAPI app is running on port 8000"
+
+      - name: Check if /health is accessible
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/health)
+          if [ $response -ne 200 ]; then
+            echo "Health check failed with status code: $response"
+            exit 1
+          else
+            content=$(curl -s http://localhost:8000/health)
+            if [[ "$content" == *"status\":\"Active"* ]]; then
+              echo "Health check passed"
+            else
+              echo "Health check failed: Unexpected content $content"
+              exit 1
+            fi
+          fi
+
   FastApi-backend:
     runs-on: ubuntu-latest
 
